import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SettingsProvider } from './context/SettingsContext'
import './globals.css'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

const appName = 'next-daisyui-starter'
const appVersion = process.env.REACT_APP_VERSION || '0.1.0-dev'

export const metadata: Metadata = {
  title: appName,
  description: `Generated by ${appName}`,
  other: {
    appName,
    appVersion,
  },
}

const devMode = process.env.NODE_ENV === 'development' && process.env.REACT_APP_DEV_MODE === 'true'

const defaultAppSettings = {
  dev: devMode,
  theme: 'dark',
}

const DynamicLayout = dynamic(() => import('./ui/Layout'), { ssr: false, })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SettingsProvider value={{ defaultValues: defaultAppSettings }}>
          <DynamicLayout title={<>{metadata.title}</>} drawer={{}}>
            {children}
          </DynamicLayout>
        </SettingsProvider>
      </body>
    </html>
  )
}
