import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Layout from './ui/Layout'
import { SettingsProvider } from './context/SettingsContext'
import appInfo from './lib/app'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: appInfo.appName,
  applicationName: appInfo.appName,
  description: `Generated by ${appInfo.appName}`,
  other: {
    version: appInfo.appVersion,
  },
}

const devMode =
  process.env.NODE_ENV === 'development' &&
  process.env.REACT_APP_DEV_MODE === 'true'

const defaultAppSettings = {
  dev: devMode,
  theme: 'dark',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SettingsProvider value={{ defaultValues: defaultAppSettings }}>
          <Layout title={<>{metadata.title}</>} drawer={{}}>
            {children}
          </Layout>
        </SettingsProvider>
      </body>
    </html>
  )
}
